### ISSUE TITLE
An alternative convention

### ISSUE THREAD

**Issue by jacksonrayhamilton** [ustun/react-without-jsx#1]
Here is another syntax that you might consider trying out or even promoting here:

``` js
var OtherComponent = React.createClass({
  render: function () {
    var $ = React.createElement;
    return (
      $('div', {className: 'example'}, 'Greetings.')
    );
  }
});

var ExampleComponent = React.createClass({
  render: function () {
    var $ = React.createElement;
    return (
      $('div', {className: 'example'},
        $('h1', null, 'Example Component'),
        $('ul', null,
          $('li', null, 'One item'),
          $('li', null, 'Another item')
         ),
        $(OtherComponent)
       )
    );
  }
});

(function () {
  var $ = React.createElement;
  ReactDOM.render(
    $(ExampleComponent),
    document.getElementById('container')
  );
}());
```

`React.createElement` allows you to create DOM elements and components using the same interface.

Also, a nice little hack: If you use 2-space indentation, Emacs indents nested elements as you intend.

There is also a "lisp" style available; I'm not sure which I like better:

``` js
return (
  $('div', {className: 'example'},
    $('h1', null, 'Example Component'),
    $('ul', null,
      $('li', null, 'One item'),
      $('li', null, 'Another item')),
    $(OtherComponent)));
```

**Comment by ustun** [comment]
Very nice, thanks. I'll add this.

The only change I want to do is to convert $ to h since people might mistake it as calling jQuery.

About 2 space, I'm actually thinking of changing, but my other work lang is Python, where I use 4, so I try to keep it consistent, but didn't know that it leads to better indentation of children.

**Comment by ustun** [comment]
Updated the README and added it as an alternative technique. See https://github.com/ustun/react-without-jsx

**Comment by ustun** [comment]
Oh, just realized 2 space work because the abbreviate is one letter :) I thought it was something in js2-mode. Yes, I'm definitely using your technique. So good.

**Comment by jacksonrayhamilton** [comment]
Nice, thanks!

I just realized that with the "closing parenthesis on newline" style, the closing parenthesis gets aligned with the opening parenthesis. That might be kind of funny for people whose indent command inserts a fixed number of spaces. So I think I do like the "lisp" style better.

**Comment by ustun** [comment]
Yes, me too. Ideally we would all write in ClojureScript. This is just a gateway drug to the real thing :)
